= vertx-pac4j-multiauth-redirect-demo

A small demo project to show how to use multi authorizations in vertx-pac4j, preventing the user from logging in multiple times via different mechanisms

To run the project, first issue the command

 mvn clean package

at the command line, and then

 java -jar target/vertx-pac4j-multiauth-demo-1.0.0-SNAPSHOT-fat.jar

To see the behaviour in action, start up the application and then direct your browser to http://localhost:8080/login

You will see that you're taken to a login page giving you two options to login.

Don't log in directly through this page (yet). Now direct your browser to http://localhost:8080/protected/test.html

You will again be taken to the login page. This time login through either option and you will proceed to the protected
test.html page. If you use the form to login, use test/test as the credentials.

Now direct yourself back to http://localhost:8080/login again. You'll see you're redirected to a default protected
landing page without being given the option to login via either mechanism (in other words if you're already logged in,
you can't log in twice).

Finally stop and restart the application and go directly to http://localhost:8080/login again. Restarting the
application will log you out (because user information is session-stored) so you will see the two options to login
again. Pick one and login and again you will be taken to the default landing page
(http://localhost:8080/protected/index.html) for an authenticated user.

